name: Maven Build

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM UTC every day

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
