name: Maven Build

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM UTC every day
    - cron: '0 16 * * *'  # Runs at 4 PM UTC every day
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true  # Allow job to continue despite failures
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Run test with Serenity framework #using commandline
      run: mvn -B verify --file pom.xml
    - name: Archive reports #generate and push report to an uploader in order to download later
      uses: actions/upload-artifact@v3
      with:
        name: serenity-report
        path: target/site/serenity
